#!/bin/bash

function print_usage {
  script_name=$(basename $0)
  cat <<EOF
Usage:
 - $script_name <src> <dest>
EOF
}

set -o nounset

function abort_check {
  if [ $1 != 0 ] ; then
    echo "Aborted"
    exit $1
  fi
}

src_file=$1
dest_dir=$2

echo "cloner $src_file $dest_dir"
mkdir -p $dest_dir

# --partial  (allows continuation from partial transfer, otherwise it is deleted)
# --whole-file  (skips delta transfer algorithm)
# --temp-dir=DIR  (scratch directory on receiver, i think this defaults to receive dir)
rsync --verbose --times --timeout=10 --whole-file "$src_file" "$dest_dir" ; abort_check $?
