#!/bin/bash

function print_usage {
  script_name=$(basename $0)
  cat <<EOF
Usage:
 - $script_name <src> <dest>
EOF
}

set -o nounset

function abort_check {
  if [ $1 != 0 ] ; then
    echo "Aborted"
    exit $1
  fi
}

echo "cloner $1 $2"
rsync --verbose --times $1 $2 ; abort_check $?
