#!/bin/bash

# TODO merge with cloner

function print_usage {
  script_name=$(basename $0)
  cat <<EOF
Usage:
 - $script_name <src> <dest>
EOF
}

set -o nounset

function abort_check {
  if [ $1 != 0 ] ; then
    echo "Aborted"
    exit $1
  fi
}

src_file=$1
dest_id=$2
dest_file=/tmp/presences/$dest_id
dest_dir=$(dirname "$dest_file")

echo "present: $src_file -> $dest_file"
mkdir -p "$dest_dir"

# TODO check src exists?

# --partial  (allows continuation from partial transfer, otherwise it is deleted)
# --whole-file  (skips delta transfer algorithm)
# --temp-dir=DIR  (scratch directory on receiver, i think this defaults to receive dir)
# --timeout=SECS  (IO timeout in seconds)
rsync --verbose --times --timeout=20 --whole-file "$src_file" "$dest_file" ; abort_check $?
