#!/bin/bash

## create options, default to NTFS non-dynamic


function print_usage {
  script_name=$(basename $0)
  cat <<EOF
Usage:
 - $script_name stage <location> <path>
 - $script_name unstage <location> <path>
 - $script_name mount <location> <path> <password>
 - $script_name unmount <location> <path>
 - $script_name open <location> <path> <password>
 - $script_name close <location> <path>
 - $script_name flush
EOF
}

set -o nounset

function abort_check {
  if [ $1 != 0 ] ; then
    echo "Aborted"
    exit $1
  fi
}

function do_stage {
  if [ ! -d $gate_mount ] ; then
    mkdir -p $gate_mount
  fi

  if [ $(mount | grep $gate_mount -c) == 0 ] ; then
    echo "Mounting"
    #TODO  rw / ro depending on gate mode
    CIFS_USER=wmtdev
    CIFS_PASS=***REMOVED***
    sudo mount -t cifs //$gate_location $gate_mount --verbose -o _netdev,rw,noexec,user=$CIFS_USER,password=$CIFS_PASS
    if [ $? != 0 ] ; then
      CIFS_USER=sqatest
      CIFS_PASS=***REMOVED***
      sudo mount -t cifs //$gate_location $gate_mount --verbose -o _netdev,rw,noexec,user=$CIFS_USER,password=$CIFS_PASS
      return $?
    fi
  fi
}

function do_unstage {
  sudo umount $gate_mount
  if [ $? != 0 ] ; then
    return $?
  fi
}

function do_mount {
  gate_password=$1

  if [ ! -d $gate_crypt ] ; then
    mkdir -p $gate_crypt
    touch $gate_crypt/closed
  fi

  if [ $(sudo truecrypt -t -l --non-interactive | grep $gate_crypt -c) == 0 ] ; then
    echo "Opening"
    sudo truecrypt -t --non-interactive --password=$gate_password $gate_mount/$gate_path $gate_crypt --fs-options="uid=$(id -u $gate_user),gid=$(id -g $gate_user)"
    if [ $? != 0 ] ; then
      return $?
    fi
  fi

  if [ $? != 0 ] ; then return $? ; fi

  #TODO check for closed tag file here

  echo "Gate opened on '$gate_crypt'"
}

function do_unmount {
  if [ -d $gate_crypt ] ; then
    if [ $(sudo truecrypt -t -l --non-interactive | grep $gate_crypt -c) != 0 ] ; then
      sudo truecrypt -t --non-interactive -d $gate_mount/$gate_path
    fi
  fi

  if [ $? != 0 ] ; then return $? ; fi

  echo "Gate closed"
}

function do_open {
  do_stage
  if [ $? != 0 ] ; then return $? ; fi
  do_mount $1
  if [ $? != 0 ] ; then return $? ; fi
}

function do_close {
  do_unmount
  if [ $? != 0 ] ; then return $? ; fi
  do_unstage
  if [ $? != 0 ] ; then return $? ; fi
}

function do_flush {
  sudo truecrypt -t --non-interactive -d --force
  sudo umount $gate_mount_root/*/fs
  sudo killall -u $gate_user rsync
}

gate_mount_root=/tmp/gates
gate_user=$(id -un)

function setup_env {
  gate_location=$1
  gate_location_desc=$(echo $gate_location | sed 's,[ /],-,g')
  gate_path=$2
  gate_path_desc=$(echo $gate_path | sed 's,[ /],-,g')
  gate_mount=$gate_mount_root/$gate_location_desc/fs
  gate_crypt=$gate_mount_root/$gate_location_desc/crypt-$gate_path_desc
}

if [ "$#" == "0" ] ; then
  print_usage ; exit 1
fi

# For all operations, pause such that the output will be trapped correctly.
sleep 2s

case "$1" in
  stage) setup_env $2 $3 ; do_stage ;;
  unstage) setup_env $2 $3 ; do_unstage ;;
  mount) setup_env $2 $3 ; do_mount $4 ;;
  unmount) setup_env $2 $3 ; do_unmount ;;
  open) setup_env $2 $3 ; do_open $4 ;;
  close) setup_env $2 $3 ; do_close ;;
  flush) do_flush ;;
  *) print_usage ; exit 1 ;;
esac
