#!/bin/bash
mysql -u root -p --database=ootw -e '
update Gateway set scoured=TIMESTAMP(CURDATE()) where source=1 and scoured > TIMESTAMP(CURDATE());
update Gateway set failed=TIMESTAMP(CURDATE()) where source=1 and failed > TIMESTAMP(CURDATE());
update Gateway set requested=TIMESTAMP(CURDATE()) where source=1 and requested > TIMESTAMP(CURDATE());'
