#!/bin/bash
#update Gateway set failed=TIMESTAMP(CURDATE()) where source=1 and failed > TIMESTAMP(CURDATE());
mysql -u root -p --database=ootw -e '
update Gateway set scourAsap=true where source=1;
update Gateway set requested=TIMESTAMP(CURDATE()) where source=1 and requested > TIMESTAMP(CURDATE());'
